Ejercicio_1:
	iverilog -Wall -o Ejercicio1.out MiniAlu_E1.v Module_ROM_E1.v Collaterals.v RAM.v Defintions.v TestBench_E1.v && vvp Ejercicio1.out && gtkwave Ejercicio1.vcd Ejercicio1.gtkw &

Ejercicio_2:
	iverilog -Wall -o Ejercicio2.out MiniAlu_E2.v Module_ROM_E2.v Collaterals.v RAM.v Defintions.v TestBench_E2.v && vvp Ejercicio2.out && gtkwave Ejercicio2.vcd Ejercicio2.gtkw &

Ejercicio_3:
	iverilog -Wall -o Ejercicio3.out MiniAlu_E3.v Module_ROM_E3.v Collaterals.v RAM.v Defintions.v TestBench_E3.v && vvp Ejercicio3.out && gtkwave Ejercicio3.vcd Ejercicio3.gtkw &

Ejercicio_4:
	iverilog -Wall -o Ejercicio4.out MiniAlu_E4.v Module_ROM_E4.v Collaterals.v RAM.v Defintions.v TestBench_E4.v && vvp Ejercicio4.out && gtkwave Ejercicio4.vcd Ejercicio4.gtkw &

clean:
	rm Ejercicio1.out Ejercicio1.vcd Ejercicio2.out Ejercicio2.vcd Ejercicio3.out Ejercicio3.vcd Ejercicio4.out Ejercicio4.vcd

clean_E1:
	rm Ejercicio1.out Ejercicio1.vcd

clean_E2:
	rm Ejercicio2.out Ejercicio2.vcd

clean_E3:
	rm Ejercicio3.out Ejercicio3.vcd

clean_E4:
	rm Ejercicio4.out Ejercicio4.vcd
