Ejercicio_1:
	iverilog -Wall -o Ejercicio1.out LCD_Control.v LCD_Writer.v Writer_Enabler.v Collaterals.v Defintions.v TestBench_LCD.v && vvp Ejercicio1.out && gtkwave Ejercicio1.vcd Ejercicio1.gtkw &
	
//clean:
//	rm Ejercicio1.out Ejercicio1.vcd Ejercicio2.out Ejercicio2.vcd Ejercicio3.out Ejercicio3.vcd Ejercicio4.out Ejercicio4.vcd

clean_E1:
	rm Ejercicio1.out Ejercicio1.vcd

